services:
  web:
    image: onlinechat
    build: .
    ports:
      - "7027:7027"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7027
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=OnlineChat;Username=postgres;Password=admin;
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: OnlineChat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

volumes:
  postgres_data:
